name: cidadao
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  brasil_fields: ^1.15.0
  camera: ^0.11.0+2
  carousel_slider: ^5.0.0
  dio: ^5.6.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  password_strength_checker: ^1.2.4
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_launcher_icons:
  image_path_android: "assets/icons/icon_android.png"
  image_path_ios: "assets/icons/icon_android.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
